server:
  port: 10002
spring:
  datasource:
    username: ddim
    password: 12348765
    url: jdbc:mysql://10.255.208.45:8888/mobile_mina?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: mina-service
  zipkin:
      base-url: http://localhost:9999
  sleuth:
    sampler:
      percentage: 1.0    #0.1--1.0  链路跟踪的数据上传的概率是多大
  redis:
    host: 10.4.94.136
    port: 18385
    timeout: 500
  cache:
    ehcache:
      config: classpath:ehcache-config.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
  instance:
    prefer-ip-address: true
logging:
  config: classpath:logback.xml
    path: /log/log/springcloud-minaservice.log
    level: com.springcloud.minaportal
 #释放所有端口
security:
    enabled: false
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  config-location: classpath:mybatis-config.xml
